name: GitHub Action 

on: [push]

jobs: 
  my-github-action:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: create a docker image 
        run: docker build -t hamsa .
      
      - name: run the docker image and lint
        run: docker run --rm hamsa npm run format 

      - name: Log Success
        run: echo "Build and tests were successful!"


