name: GitHub Action 

on: [push]

jobs: 
  my-github-action:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: linting
        run: npm run format 
    


