name: GitHub Action 

on: [push]

jobs: 
  my-github-action:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Fix permissions
        run: chmod +x ./node_modules/.bin/prettier

      - name: Install dependencies
        run: npm install
        

      - name: linting
        run: npm run format 
    



    


